name: Workflow 1
on: 
  push:
    branches: [ main ]
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Print Greeting
        run: echo "Hello, World!"
      - name: Print Ending Message
        run: echo "Done, GoodBye!"
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting In Ubuntu
        run: echo "Welcome to ubuntu"
  build:
    needs: test
    runs-on: macos-latest
    steps:
      - name: Print Greeting In MACOS
        run: echo "Welcome To MacOs"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Parallel Step
        run: echo " This is a Parallel Step"