name: Workflow 1
on: 
  push:
    branches: [ main ]
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Print Greeting
        run: echo "Hello, World!"
      - name: Print Ending Message
        run: echo "Done, GoodBye!"
  second-job:
    needs: first-job
    runs-on: ubuntu-lates
    steps:
      - name: Print Greeting In Ubuntu
        run: echo "Welcome to ubuntu"
  third-job:
    needs:  second-job
    runs-on: macos-latest
    steps:
      - name: Print Greeting In MACOS
        run: echo "Welcome To MacOs"